// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsAhaRMEV0O0aNHOOXVVrZrhqmQ14Olkg',
    appId: '1:237831475435:web:4052066e4f52d8949d2eae',
    messagingSenderId: '237831475435',
    projectId: 'golivin-id',
    authDomain: 'golivin-id.firebaseapp.com',
    storageBucket: 'golivin-id.appspot.com',
    measurementId: 'G-RT54G7H4W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH6wxu_iVffVKaqTuIgidNuowBgAXapHY',
    appId: '1:237831475435:android:1accfdf265c270fe9d2eae',
    messagingSenderId: '237831475435',
    projectId: 'golivin-id',
    storageBucket: 'golivin-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXfx5F2OQaYM2_35sUMf3xQm6n1Bwnqc0',
    appId: '1:237831475435:ios:02ab2e846679b2859d2eae',
    messagingSenderId: '237831475435',
    projectId: 'golivin-id',
    storageBucket: 'golivin-id.appspot.com',
    iosClientId:
        '237831475435-15lbjs1pcs63j8l5j2c3vs9qhp9a6v74.apps.googleusercontent.com',
    iosBundleId: 'com.golivin.app',
  );
}
