// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqBPXiPexy-sYfwFnLaq8IBvrfnO4ePwY',
    appId: '1:186598973704:web:52483f84c4ff8e0b47ccbd',
    messagingSenderId: '186598973704',
    projectId: 'golivin-170222',
    authDomain: 'golivin-170222.firebaseapp.com',
    storageBucket: 'golivin-170222.appspot.com',
    measurementId: 'G-2MLVPVPQZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFT2xeVN7X1FLTj_awzAMIFpjic20OgY8',
    appId: '1:186598973704:android:924ecd92c33fbaed47ccbd',
    messagingSenderId: '186598973704',
    projectId: 'golivin-170222',
    storageBucket: 'golivin-170222.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGZm6ZsUTt5n-tsc0KqF-n6GTMuuKct6A',
    appId: '1:186598973704:ios:55625e797a1cc7ff47ccbd',
    messagingSenderId: '186598973704',
    projectId: 'golivin-170222',
    storageBucket: 'golivin-170222.appspot.com',
    iosClientId: '186598973704-405olbgm197nnekr4d4mnknnk32ulput.apps.googleusercontent.com',
    iosBundleId: 'com.golivin.app',
  );
}
